### ISSUE TITLE
EOS-27621: Sync to Jira?

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-k8s#17]
Hello @john-a-fletcher . The other cortx repos have an integration set up such that new issues created in github get automatically mirrored into jira and future updates on the jira side get mirrored also to github. Note that new issues created in jira are NOT mirrored to github (i.e. we do it safely so that community things are mirrored but internal things are not). 

Do you want us to set this up for this repo as well?

**Comment by osowski** [comment]
@johnbent Yes, please set this up. I'll connect with you to determine exactly what and where in JIRA.

**Comment by johnbent** [comment]
Created https://jts.seagate.com/browse/EOS-27329 to get this done.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27621. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

Cool. Looks like this was done. We can close this now.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

The current integration opens issues in Jira but they just end up in the aether. 

*Can we have these issues opened with Component = `K8s Orch` by default?*

Otherwise they will fall through the cracks.

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

Can we get this to update to using specific components to auto-route them to our team? Otherwise, we are not seeing them in any of our Boards/views?

 

[~747271]  Can you set Component of `K8s Orch` for issues originating from [https://github.com/Seagate/cortx-k8s] ?

**Comment by cortx-admin** [comment]
> John Bent commented in Jira Server:

[~519663] and [~519455], can you help please to create a Jira component of 'K8s Orch'?

**Comment by cortx-admin** [comment]
> Richard Osowski commented in Jira Server:

The component exists, we just need to Board Genius automation to set it on the Jira issues it opens.

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Rick, let me address this request in next Sprint

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

[~938416], Sure but Board genius has component to label mapping so I can set the label in BG as,

 

!image-2022-02-03-10-02-35-946.png!

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

please refer the mapping of fields between Jira and GitHub Issues as documented in https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/617481393/1+1+Mapping+of+FIELDS+between+Jira+and+GitHub+Issues

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

label has been changed i.e. github_cortx_k8s_orch for cortx-k8s repo which is mapped to component in Board Genius

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Done

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Closed on behalf of reporter
