### ISSUE TITLE
Getting permission denied while trying to setup cortx-k8s

### ISSUE THREAD

**Issue by alfhad** [Seagate/cortx-k8s#42]
Error while trying to follow the steps in the below document :
https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md

While trying to execute step number 2.7 I am getting the following error :

```
# ssh $SSH_FLAGS centos@$ClusterControlPlaneIP "kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml; kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml"
Warning: Permanently added 'XX.XXX.XX.XXX' (ED14408) to the list of known hosts.
error: error loading config file "/home/centos/.kube/config": open /home/centos/.kube/config: permission denied
error: error loading config file "/home/centos/.kube/config": open /home/centos/.kube/config: permission denied
```

**Comment by gregnsk** [comment]
Please check if /home/centos/.kube/config exists and is accessible by centos user.

Have you completed the previous step? 
ssh $SSH_FLAGS centos@$ClusterControlPlaneIP "mkdir -p .kube; sudo cp -i /etc/kubernetes/admin.conf .kube/config; sudo chown $(id -u):$(id -g) .kube/config"

**Comment by alfhad** [comment]
> Please check if /home/centos/.kube/config exists and is accessible by centos user.
> 
> Have you completed the previous step? ssh $SSH_FLAGS centos@$ClusterControlPlaneIP "mkdir -p .kube; sudo cp -i /etc/kubernetes/admin.conf .kube/config; sudo chown $(id -u):$(id -g) .kube/config"

Yes I ran the previous step and it was successful, I didn't get any errors or warning there.
Also, the directory ```/home/centos/.kube/config``` does exist and is accessible by centos user

**Comment by gregnsk** [comment]
Could you run the following commands:
ssh $SSH_FLAGS centos@$ClusterControlPlaneIP   - to connect to the master node

On the master node:
ls -ld /home/centos/.kube /home/centos/.kube/config
kubectl get nodes
kubectl get pods -ALL

And share the output?

**Comment by alfhad** [comment]
> Could you run the following commands: ssh $SSH_FLAGS centos@$ClusterControlPlaneIP - to connect to the master node
> 
> On the master node: 
> ls -ld /home/centos/.kube /home/centos/.kube/config
> kubectl get nodes 
> kubectl get pods -ALL
> 
> And share the output?


I ran the commands and this was the output:
```
[root@fedora cortx-k8s-cl03]# ssh $SSH_FLAGS centos@$ClusterControlPlaneIP
Warning: Permanently added 'XX.XX.XX.XXX' (ED12408) to the list of known hosts.
Last login: Mon Dec 27 11:20:42 2021 from XXX.XXX.XX.XX
[centos@ip-XXX-XX-XX-XXX ~]$ ls -ld /home/centos/.kube /home/centos/.kube/config
drwxrwxr-x. 2 centos centos   20 Dec 27 10:50 /home/centos/.kube
-rw-------. 1 root   root   5641 Dec 27 10:53 /home/centos/.kube/config
[centos@ip-XXX-XX-XX-XXX ~]$ kubectl get nodes
error: error loading config file "/home/centos/.kube/config": open /home/centos/.kube/config: permission denied
[centos@ip-XXX-XX-XX-XXX ~]$ kubectl get pods -ALL
error: error loading config file "/home/centos/.kube/config": open /home/centos/.kube/config: permission denied
```

**Comment by gregnsk** [comment]
please run on the master node:
sudo chown centos:centos /home/centos/.kube/config

**Comment by alfhad** [comment]
> please run on the master node: sudo chown centos:centos /home/centos/.kube/config

This worked !! Thanks alot!

**Comment by gregnsk** [comment]
Great, glad it helped. Please share your experience with CORTX.
