### ISSUE TITLE
Complete "Using CORTX on Kubernetes" in root README

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#68]
The https://github.com/Seagate/cortx-k8s/tree/integration#using-cortx-on-kubernetes section needs to be completed to have a quick, high-level usage guide for interacting with CORTX once it is deployed. A deeper-dive can be linked off to another document in the repository for a comprehensive user guide once deployed, but we should have some level of a smoke test under the root README quick starts section.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28450. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by gregnsk** [comment]
@osowski - what would you add to https://github.com/Seagate/cortx-k8s/blob/main/doc/cortx-aws-k8s-installation.md#4-using-cortx?

**Comment by osowski** [comment]
> @osowski - what would you add to https://github.com/Seagate/cortx-k8s/blob/main/doc/cortx-aws-k8s-installation.md#4-using-cortx?

From a concept point of view, we could point directly to that. 

**I want to move away from making this overarching statement _"We recommend to run the following commands on the Kubernetes control plane node"_, as it is an anti-pattern we do not want to double-down on.**

The only edit that I see we would need to make is the removal of that direction, as well as updating the CSM_IP commands to point to the `cortx-control-loadbal-svc` instead (and previously configure it via NodePort if not in a Public Cloud environment).

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
