### ISSUE TITLE
cortx-aws-k8s-installation.md requires updates to include specific versions used in deployment

### ISSUE THREAD

**Issue by osowski** [Seagate/cortx-k8s#73]
The current cortx-aws-k8s-installation.md documentation does not specify which version of the https://github.com/Seagate/cortx-k8s/releases codebase is used for deployment. This causes issues since there has been a rearchitecture of Data & Server components and certain commands need to be updated to reflect which component the end user is expecting to interact with. 

We need to include a specific tagged version in [Step 3.1](https://github.com/Seagate/cortx-k8s/blob/main/doc/cortx-aws-k8s-installation.md#31-clone-cortx-k8s-framework), as well as the associated tested and released `cortx-all` container image for default user interaction and deployment. As well as updating the existing instructions to match the current architecture.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28465. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
@osowski I see that the current version of this doc in step 3.1 has checked out code at tag "v0.0.22": 
```
git clone -b v0.0.22 https://github.com/Seagate/cortx-k8s.git
``` 
Hence IMHO this issue is no longer valid. Please correct me if I am wrong or I have missed anything.

**Comment by osowski** [comment]
> @osowski I see that the current version of this doc in step 3.1 has checked out code at tag "v0.0.22":
> 
> ```
> git clone -b v0.0.22 https://github.com/Seagate/cortx-k8s.git
> ```
> 
> Hence IMHO this issue is no longer valid. Please correct me if I am wrong or I have missed anything.

Good catch! Thanks for looking through this and finding that it's already there!

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

na

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub

**Comment by cortx-admin** [comment]
> Walter Lopatka commented in Jira Server:

Closed in GitHub
